-- AULA 1: SELECT + DESAFIO
SELECT
-- SQL Server, Postgres, Oracle, mySQL

SELECT coluna1, coluna2
FROM tabela;

SELECT *
FROM tabela;

-- DESAFIO 1
-- EQUIPE DE MARKETING PRECISA FAZER UMA PESQUISA SOBRE NOMES MAIS COMUNS DE SEUS CLIENTES E PRECISA DO NOME E SOBRENOME DE TODOS OS CLIENTES QUE ESTÃO CADASTRADOS NO SISTEMA.
SELECT FirstName, LastName
FROM person.Person;




-- AULA 2: DISTINCT + DESAFIO
SELECT DISTINCT coluna1, coluna2
FROM tabela;
-- DISTINCT: RETORNA APENAS OS DADOS ÚNICOS DE UMA TABELA

-- DESAFIO 2
-- QUANTOS NOMES SOBRENOMES ÚNICOS TEMOS EM NOSSA TABELA Person.Person?
SELECT DISTINCT LastName
FROM person.Person;




-- AULA 3: WHERE + DESAFIO
SELECT coluna1, coluna2, coluna_n
FROM tabela
WHERE condicao;

-- COMENTÁRIOS NO SQL PODEM SER FEITOS COM "--" OU "/* */"

/* 

OPERADOR    -   DESCRIÇÃO
=               IGUAL
>               MAIOR QUE
<               MENOR QUE
>=              MAIOR QUE OU IGUAL
<=              MENOR QUE OU IGUAL
<>              DIFERENTE DE
AND             OPERADOR LÓGICO E
OR              OPERADOR LÓGICO OU

*/

SELECT *
FROM person.Person
WHERE LastName = 'Miller' AND FirstName = 'Anna';

SELECT *
FROM production.Product
WHERE color = 'blue' OR color = 'black';

SELECT *
FROM production.Product
WHERE ListPrice > 1500;

SELECT *
FROM production.Product
WHERE ListPrice > 1500 AND ListPrice < 5000;

SELECT *
FROM production.Product
WHERE color <> 'red';

-- DESAFIO 3
-- EQUIPE DE PRODUÇÃO DE PRODUTOS PRECISA DO NOME DE TODAS AS PEÇAS QUE PESAM MAIS QUE 500kg MAS NÃO MAIS QUE 700kg PARA INSPEÇÃO
SELECT Name
FROM Production.Product
WHERE Weight > 500 AND Weight <= 700;

-- DESAFIO 4
-- FOI PEDIDO PELO MARKETING UMA RELAÇÃO DE TODOS OS EMPREGADOS (EMPLOYEES) QUE SÃO CASADOS (SINGLE = SOLTEIRO, MARRIED = CASADO) E SÃO ASALARIADOS (SALARIED)
SELECT *
FROM HumanResources.Employee
WHERE MaritalStatus = 'Ms' AND SalariedFlag = 1;

-- DESAFIO 5
-- UM USUÁRIO CHAMADO PETER KREBS ESTÁ DEVENDO UM PAGAMENTO, CONSIGA O EMAIL DELE PARA QUE POSSAMOS ENVIAR UMA COBRANÇA!
-- (TERÁ QUE USAR A TABELA person.Person E DEPOIS A TABELA person.EmailAddress)
SELECT *
FROM person.Person
WHERE FirstName = 'Peter' AND LastName = 'Krebs';

SELECT *
FROM person.EmailAddress
WHERE BusinessEntityID = 26;




-- AULA 4: COUNT + DESAFIO
SELECT COUNT(DISTINCT coluna1)
FROM tabela;
-- COUNT: RETORNA O TOTAL DE LINHAS SELECIONADAS

SELECT COUNT(*)
FROM person.Person;

SELECT COUNT(title)
FROM person.Person;

SELECT COUNT(DISTINCT title)
FROM person.Person;

-- DESAFIO 6
-- EU QUERO SABER QUANTOS PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA DE PRODUTOS
-- (production.Product)
SELECT COUNT(product)   
FROM production.Product;

-- DESAFIO 7
-- EU QUERO SABER QUANTOS TAMANHOS TEMOS CADASTRADOS EM NOSSA TABELA
SELECT COUNT(size)
FROM production.Product;

-- DESAFIO 8
-- EU QUERO SABER QUANTOS TAMANHOS DIFERENTES DE PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA
SELECT COUNT(DISTINCT size)
FROM production.Product;




-- AULA 5: TOP
SELECT TOP 10 *
FROM tabela;
-- TOP: ESPECIFICA O NÚMERO DE REGISTROS A RETORNAR




-- AULA 6: ORDER BY + DESAFIO
SELECT coluna1, coluna2
FROM tabela
ORDER BY coluna1 ASC/DESC;
-- ORDER BY: EFETUA A ORDERNAÇÃO EM ORDEM CRESCENTE/DECRESCENTE

SELECT *
FROM person.Person
ORDER BY FirstName ASC;
-- ASC: FORMA CRESCENTE

SELECT *
FROM person.Person
ORDER BY FirstName DESC;
-- DESC: FORMA DECRESCENTE

SELECT *
FROM person.Person
ORDER BY FirstName ASC, LastName DESC;

SELECT FirstName, LastName
FROM person.Person
ORDER BY FirstName ASC, LastName DESC;

SELECT FirstName, LastName
FROM person.Person
ORDER BY MiddleName ASC;

SELECT *
FROM person.Person

-- DESAFIO 9
-- OBTER O productId DOS 10 PRODUTOS MAIS CAROS CADASTRADOS NO SISTEMA, LISTANDO DO MAIS CARO PARA O MAIS BARATO

/*
DICAS:
- TERÁ QUE USAR A TABELA production.Product
- TERÁ QUE USAR O ORDER BY E TOP
- PARA ORDENAR TERÁ QUE USAR O ORDER BY ASC OU DESC DEPENDENDO DO RESULTADO QUE ESTÁ BUSCANDO
 */

SELECT TOP 10 productId
FROM production.Product
ORDER BY ListPrice DESC;

-- DESAFIO 10
-- OBTER O NOME E NUMERO DO PRODUTO DOS PRODUTOS QUE TEM O productId entre 1~4
SELECT TOP 4 name, productNumber
FROM production.Product
ORDER BY productId ASC;




-- AULA 7: BETWEEN
-- BETWEEN: É USADO PARA ENCONTRAR VALOR ENTRE UM VALOR MÍNIMO E VALOR MÁXIMO
-- valor BETWEEN mínimo AND máximo;
SELECT *
FROM production.Product
WHERE ListPrice BETWEEN 1000 AND 1500;

-- LISTA O OPOSTO
SELECT *
FROM production.Product
WHERE ListPrice NOT BETWEEN 1000 AND 1500;

SELECT *
FROM HumanResources.Employee
WHERE HireDate BETWEEN '2009-01-01' AND '2010-01-01';
ORDER BY HireDate;




-- AULA 8: IN
-- O OPERADOR 'IN' É USADO JUNTAMENTE AO WHERE!
-- PARA VERIFICAR SE UM VALOR CORRESPONDEM COM QUALQUER VALOR PASSADO NA LISTA DE VALORES
-- valor IN (valor1, valor2)
-- valor IN (SELECT valor FROM nomeDaTabela)
SELECT *
FROM person.Person
WHERE BusinessEntityID IN (2, 7, 13);

-- ACIMA MOSTRA UMA MANEIRA SIMPLIFICADA COM O COMANDO IN

SELECT *
FROM person.Person
WHERE BusinessEntityID = 2 OR BusinessEntityID = 7 OR BusinessEntityID = 13;




-- AULA 9: LIKE
SELECT *
FROM person.Person
WHERE FirstName LIKE 'ovi%';

SELECT *
FROM person.Person
WHERE FirstName LIKE '%to';

SELECT *
FROM person.Person
WHERE FirstName LIKE '%essa%';

-- AQUI SUBSTITUI APENAS UM CARACTERE
SELECT *
FROM person.Person
WHERE FirstName LIKE '%ro_';

SELECT *
FROM person.Person
WHERE FirstName LIKE '%rO_';




-- AULA 10: DESAFIOS FUNDAMENTOS SQL
-- QUANTOS PRODUTOS TEMOS CADASTRADO NO SISTEMA QUE CUSTAM MAIS QUE 1500 DÓLARES?
-- TERÁ QUE USAR A TABELA production.Product
-- TERÁ QUE USAR COUNT E WHERE E MAIS ALGUM OPERADOR QUE COMPARAÇÃO
SELECT COUNT (ListPrice)
FROM production.Product
WHERE ListPrice > 1500;

-- QUANTAS PESSOAS TEMOS COM O SOBRENOME QUE INICIA COM A LETRA P?
-- TERÁ QUE USAR A TABELA person.Person
-- TERÁ QUE USAR O COUNT, WHERE E LIKE
SELECT COUNT(LastName)
FROM person.Person
WHERE LastName LIKE 'p%';

-- EM QUANTAS CIDADES ÚNICAS ESTÃO CADASTRADOS NOSSOS CLIENTES?
-- TERÁ QUE USAR A TABELA person.Person
-- TERÁ QUE USAR COUNT, DISTINCT
SELECT COUNT(DISTINCT(city))
FROM person.Address;

-- QUAIS SÃO AS CIDADES ÚNICAS QUE TEMOS CADASTRADOS EM NOSSO SISTEMA?
-- TERÁ QUE USAR A TABELA person.Address
-- SERÁ BEM SIMILAR A RESPOSTA ANTERIOR
SELECT DISTINCT(city)
FROM person.Address;

-- QUANTOS PRODUTOS VERMELHOS TEM PREÇO ENTRE 500 A 1000 DÓLARES?
-- TERÁ QUE USAR A TABELA production.Product
-- TERÁ QUE USAR WHERE, BETWEEN
SELECT COUNT(*)
FROM production.Product
WHERE color = 'red'
AND ListPrice BETWEEN 500 AND 1000;

-- QUANTOS PRODUTOS CADASTRADOS TEM A PALAVRA 'road' NO NOME DELES?
-- TERÁ QUE USAR A TABELA production.Product
-- TERÁ QUE USAR COUNT, LIKE
SELECT COUNT(*)
FROM production.Product
WHERE name LIKE '%road%';




-- AULA 11: MIN MAX SUM AVG
-- FUNÇÕES DE AGREGAÇÃO BASICAMENTE AGREGAM OU COMBINAM DADOS DE UMA TABELA EM 1 RESULTADO SÓ
-- SUM: SOMA DE COLUNAS
-- MIN: MENOR VALOR DAS COLUNAS
-- MAX: MAIOR VALOR DAS COLUNAS
-- AVG: MÉDIA DOS VALORES DAS COLUNAS

SELECT TOP 10 *
FROM Sales.SalesOrderDetail;

-- RETORNARÁ O TOTAL DE TODAS AS COLUNAS DE 'linetotal'
SELECT TOP 10 SUM(linetotal)
FROM Sales.SalesOrderDetail;

-- RETORNARÁ O TOTAL DE TODAS AS COLUNAS DE 'linetotal' NOMEADO COMO 'Soma'
SELECT TOP 10 SUM(linetotal) AS "Soma"
FROM Sales.SalesOrderDetail;

-- RETORNARÁ O MENOR VALOR CADASTRADO NA COLUNA DE 'LINEtotal'
SELECT TOP 10 MIN(LINEtotal)
FROM Sales.SalesOrderDetail;

-- RETORNARÁ O MAIOR VALOR CADASTRADO NA COLUNA DE 'LINEtotal'
SELECT TOP 10 MAX(LINEtotal)
FROM Sales.SalesOrderDetail;

-- RETORNARÁ A MÉDIA DA COLUNA DE 'LINEtotal'
SELECT TOP 10 AVG(LINEtotal)
FROM Sales.SalesOrderDetail;




-- AULA 12: GROUP BY + DESAFIOS (INTERMEDIÁRIO)
-- GROUP BY: DIVIDE O RESULTADO DA SUA PESQUISA EM GRUPOS
-- PARA CADA GRUPO VOCÊ PODE APLICAR UM FUNÇÃO DE AGREGAÇÃO, POR EXEMPLO:
-- CALCULAR A SOMA DE ITENS
-- CONTAR O NÚMERO DE ITENS NAQUELE GRUPO
SELECT coluna1, funcaoAgregacao(coluna2)
FROM nomeDaTabela
GROUP BY coluna1;

SELECT * 
FROM Sales.SalesOrderDetail;

SELECT SpecialOfferID, SUM(UnitPrice) AS "SOMA"
FROM Sales.SalesOrderDetail
GROUP BY SpecialOfferID;

SELECT SpecialOfferID, UnitPrice
FROM Sales.SalesOrderDetail
WHERE SpecialOfferID = 9;

-- VAMOS DIZER QUE EU QUERO SABER QUANTOS CADA PRODUTO FOI VENDIDO ATÉ HOJE
SELECT * FROM Sales.SalesOrderDetail

-- AGRUPOU TODOS OS PRODUTOS DE 707 E QUANTAS VEZES ELE APARECE NO BANCO DE DADOS
SELECT ProductId, COUNT(ProductId) AS "CONTAGEM"
FROM Sales.SalesOrderDetail
GROUP BY ProductId;

-- VAMOS DIZER QUE EU QUERO SABER QUANTOS NOMES DE CADA NOME TEMOS CADASTRADO EM NOSSO BANCO DE DADOS
SELECT FirstName, COUNT(FirstName) AS "CONTAGEM"
FROM Person.Person
GROUP BY FirstName;

-- NA TABELA production.product EU QUERO SABER A MÉDIA DE PREÇO PARA OS PRODUTOS QUE SÃO PRATAS (silver)
SELECT color, AVG(ListPrice) "PREÇO"
FROM Production.Product
WHERE color = 'Silver'
GROUP BY color;

-- DESAFIO 11
-- EU PRECISO SABER QUANTAS PESSOAS TEM O MESMO MiddleName AGRUPADAS POR O MiddleName
-- DICAS:
-- TABELA Person.Person
-- USAR GROUP BY E UMA FUNÇÃO DE AGREGAÇÃO
SELECT MiddleName, COUNT(MiddleName) AS "quantidade"
FROM Person.Person
GROUP BY MiddleName

-- EU PRECISO SABER EM MÉDIA QUAL É A QUANTIDADE (quantity) QUE CADA PRODUTO É VENDIDO NA LOJA.
-- DICAS:
-- TABELA Sales.SalesOrderDetail
-- USAR GROUP BY E UMA FUNÇÃO DE AGREGAÇÃO
SELECT ProductID, AVG(OrderQty) "media"
FROM Sales.SalesOrderDetail
GROUP BY ProductID;

-- EU QUERO SABER QUAL FORAM AS 10 VENDAS QUE NO TOTAL TIVERAM OS MAIORES VALORES DE VENDA (line total) POR PRODUTO DO MAIOR VALOR PARA O MENOR
-- DICAS:
-- TABELA Sales.SalesOrderDetail
-- USAR GROUP BY E UMA FUNÇÃO DE AGREGAÇÃO
-- SE ATENTAR A POR O QUE VOCÊ ESTÁ ORDENANDO
SELECT TOP 10 ProductID, SUM(linetotal)
FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY SUM(linetotal) DESC;

-- EU PRECISO SABER QUANTOS PRODUTOS E QUAL A QUANTIDADE MÉDIA DE PRODUTOS TEMOS CADASTRADOS NAS NOSSAS ORDEM DE SERVIÇO (WorkOrder), AGRUPADOS POR ProductID
-- DICAS:
-- TABELA production.workorder
-- USAR GROUP BY E UMA FUNÇÃO DE AGREGAÇÃO
SELECT ProductID, COUNT(ProductID) "contagem"
AVG(OrderQty) AS "media"
FROM Production.WorkOrder
GROUP BY ProductID;




-- AULA 13: HAVING
-- ...
